GAME         := solar_fox
SRC_DIR      := vhdl_solar_fox_rev_0_1_2019_11_22
TOP_ENTITY   := solar_fox_basys3
IO_SUMMARY   := PS/2 keyboard (JB) + JA joystick OR-merged; btnU=coin1, btnL=fast1(start), btnC=reset; JC PmodAMP2 mono audio (left channel of stereo core); sw(14)=amp shutdown, sw(15)=amp gain
DISPLAY_HINT := F8: 31 kHz VGA / 15 kHz TV

include ../tools/mk/machine.mk
