GAME         := computer_space
SRC_DIR      := vhdl_computer_space_rev_1_1_2017_11_22
TOP_ENTITY   := computer_space_basys3
DISPLAY_NAME := Computer Space
IO_SUMMARY   := Onboard USB HID keyboard (C17/B17) + JA joystick OR-merged (rotate/thrust/fire); btnU/D/L/R=start (any); btnC=reset; JC PmodAMP2 PWM audio; sw(14)=amp shutdown, sw(15)=amp gain, sw(13)=display mode; VGA 4-4-4 RGB via MiST scandoubler
DISPLAY_HINT := sw(13): 0 = 31 kHz VGA (scandoubled), 1 = 15 kHz TV

include ../tools/mk/machine.mk
