GAME         := burnin_rubber
SRC_DIR      := vhdl_burnin_rubber_rev_0_0_2017_12_22
TOP_ENTITY   := burnin_rubber_basys3
IO_SUMMARY   := PS/2 keyboard (JB) + JA joystick (movement+fire, fire+up=coin, fire+left=start1) OR-merged; btnC=reset; btnU/btnD=coin, btnL=P1 start, btnR=P2 start; JC PmodAMP2 PWM audio; sw(14)=amp shutdown, sw(15)=amp gain, sw(13)=display mode; VGA 4-4-4 RGB
DISPLAY_HINT := sw(13): 0 = 31 kHz VGA, 1 = 15 kHz TV

include ../tools/mk/machine.mk
