GAME         := pooyan
SRC_DIR      := vhdl_pooyan_rev_0_2_2020_04_26
TOP_ENTITY   := pooyan_basys3
DISPLAY_NAME := Pooyan
IO_SUMMARY   := PS/2 keyboard (JB) + JA joystick OR-merged; btnC=reset; JC PmodAMP2 mono PWM audio; sw(14)=sound enable, sw(15)=gain; VGA 4-4-4 RGB via vga_scandoubler
DISPLAY_HINT :=

include ../tools/mk/machine.mk
