GAME         := berzerk
SRC_DIR      := vhdl_berzerk_rev_0_1_2018_08_08
TOP_ENTITY   := berzerk_basys3
IO_SUMMARY   := PS/2 keyboard (JB) + JA joystick (movement+fire) OR-merged; btnC=reset; btnL=P1 start, btnR=P2 start, btnU/btnD=coin; JC PmodAMP2 PWM audio; sw(14)=amp shutdown, sw(15)=amp gain, sw(13)=display mode; VGA 4-4-4 RGB
DISPLAY_HINT := sw(13): 0 = 31 kHz VGA, 1 = 15 kHz TV

include ../tools/mk/machine.mk
