GAME         := sky_skipper
SRC_DIR      := vhdl_sky_skipper_rev_01_2020_01_28
TOP_ENTITY   := sky_skipper_basys3
DISPLAY_NAME := Sky Skipper (Nintendo)
IO_SUMMARY   := USB-HID keyboard; JA joystick; PmodAMP2 audio (JC); 4 pushbuttons
DISPLAY_HINT := sw(13)=0 -> 31 kHz VGA (default), sw(13)=1 -> 15 kHz TV; F8 toggles

include ../tools/mk/machine.mk
