GAME         := ckong
SRC_DIR      := vhdl_ckong_rev_0_1_2018_06_06
TOP_ENTITY   := ckong_basys3
DISPLAY_NAME := Crazy Kong (Irem M-52)
IO_SUMMARY   := USB HID keyboard (C17/B17); JA joystick; PmodAMP2 audio (JC); 4 pushbuttons
DISPLAY_HINT := sw(13) toggles 31 kHz VGA (internal line doubler) / 15 kHz TV (composite)

include ../tools/mk/machine.mk
