GAME         := time_pilot
SRC_DIR      := vhdl_time_pilot_rev_0_0_2017_11_05
TOP_ENTITY   := time_pilot_basys3
IO_SUMMARY   := PS/2 keyboard (JB) + JA Atari-style joystick OR-merged; btnC=reset; JC PmodAMP2 PWM audio; sw(14)=amp shutdown, sw(15)=amp gain; sw(7:0)=dip_switch_2 (sound/difficulty/bonus/cocktail/lives); VGA 4-4-4 RGB via scandoubler
DISPLAY_HINT :=

include ../tools/mk/machine.mk
