GAME         := phoenix
SRC_DIR      := vhdl_phoenix_DE10_lite
TOP_ENTITY   := phoenix_basys3
DISPLAY_NAME := Phoenix
IO_SUMMARY   := PS/2 keyboard (JB, only input -- JA joystick/buttons tried and reverted, see PORTING_SPEC.md); btnC=reset; dip switches sw(7:0), audio_select sw(10:8); JC PmodAMP2 PWM audio; sw(14)=sound enable, sw(15)=AMP gain, sw(13)=display mode; VGA 4-4-4 RGB
DISPLAY_HINT := sw(13): 0 = 31 kHz VGA, 1 = 15 kHz TV

include ../tools/mk/machine.mk
