GAME         := bagman
SRC_DIR      := vhdl_bagman_rev_0_1_2018_06_05
TOP_ENTITY   := bagman_basys3
IO_SUMMARY   := PS/2 keyboard (JB) + JA joystick OR-merged; btnC=reset; JC PmodAMP2 PWM audio; sw(14)=amp shutdown, sw(15)=amp gain, sw(13)=display mode; VGA 4-4-4 RGB
DISPLAY_HINT := sw(13): 0 = 31 kHz VGA, 1 = 15 kHz TV

include ../tools/mk/machine.mk
